name: create and deploy docs

on:
  push:
    branches:
      - devel

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2.2.2
      - name: Install dependencies 🔧
        run: |
          python -m pip install --upgrade pip
          pip install git+https://github.com/Feneric/doxypypy
      - name: Build docs
        uses: mattnotmitt/doxygen-action@v1.3.0
        with:
          working-directory: 'docs'
      - run: echo $(ls docs)
      - name: Push to gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/_build/html
