name: create and deploy docs

on:
  push:
    branches:
      - devel

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo $(pwd)
          echo $(ls)
      - name: Build docs
        uses: mattnotmitt/doxygen-action@v1.3.0
        with:
          working-directory: 'docs'

  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Push to gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/_build
      - name: clean up
        run: rm -rf ./docs/_build
